name: 'Docker '
# this tells when the action to run
# it runs when pull request is closed & when code is pushed to main branch
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main
  # this uses secrets you provided in your github secrets
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.DOCKER_HUB_REPO}}
jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    #
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:prod
      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:prod
